### ISSUE TITLE
Eigen 3.3 is here!

### ISSUE THREAD

**Issue by dpshelio** [astro-informatics/sopt#158]
And that's not too good... well, it's good that stuff moves forward, but not good for us at the moment as  it breaks some stuff. Jenkins is now running with 3.2.10 till we update the code to Eigen 3.3 compatible.

**Comment by dpshelio** [comment]
Eigen 3.3.4 has been released last week! We should update.

**Comment by Luke-Pratley** [comment]
We have updated
