### ISSUE TITLE
Use conan to install dependencies

### ISSUE THREAD

**Issue by tkoskela** [astro-informatics/sopt#262]
Related to https://github.com/astro-informatics/purify/issues/295

Easier to start with sopt since it has less dependencies

- [x] Write conanfile
- [x] See if all dependencies are available in conan
- [x] Replace GreatCmakeCookoff dependency lookup with conan dependencies
- [x] Compile!
  - [x] Find out why we can't find spdlog
  - [x] Find out why we can't find omp.h
  - [x] Try building on Linux -- success 🎉 

Moved remaining task to #267

## commands to build
```
conan install .. -pr=<name_of_profile>
cmake .. -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -Dlogging=OFF -Dopenmp=OFF -DCMAKE_INSTALL_PREFIX=.
make
```

**Comment by tkoskela** [comment]
Compiled successfully on Ubuntu with Eigen 3.3.7 installed through conan. There were missing references to `std::vector` and `std::time` that needed the headers explicitly included, see https://github.com/astro-informatics/sopt/pull/265/commits/223be4cf245fefceae93185f9edafca8fb2cd659

**Comment by tkoskela** [comment]
Also compiles successfully on my MacOS with gcc 11 after fixing the broken links homebrew left behind

**Comment by SJaffa** [comment]
Problem with spdlog fixed by doing the suggestion here: https://github.com/gabime/spdlog/issues/1865

**Comment by tkoskela** [comment]
For reference, add `compiler.libcxx=libstdc++11` into the conan profile

**Comment by tkoskela** [comment]
-Dopenmp=ON seems to compile now on both Ubuntu and MacOS

**Comment by SJaffa** [comment]
We should add the conan generated build files to the gitignore
