### ISSUE TITLE
Problems with libtiff provided by conan

### ISSUE THREAD

**Issue by tkoskela** [astro-informatics/sopt#272]
If we remove `find_package(TIFF)` in `dependencies.cmake` and use `libtiff` installed by conan instead we get build errors. It seems that `libtiff` installed natively on all the systems we run on so this is not a breaking issue, for example the Github Actions runners find 

```
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.1.0")  
```

while our conanfile requests
```python
  self.requires("libtiff/4.0.9")
```

# Error on MacOS Monterey 12.2.1

Both libtiff versions `4.0.9` and `4.3.0` built from source with both `gcc-11`
```bash
Undefined symbols for architecture x86_64:
  "__ZN4sopt9utilities10write_tiffERKN5Eigen5ArrayIdLin1ELin1ELi0ELin1ELin1EEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      _main in copy_tiff.cc.o
  "__ZN4sopt9utilities9read_tiffERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      _main in copy_tiff.cc.o
      __ZN4sopt12notinstalled18read_standard_tiffERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE in libtools_for_tests.a(tiffwrappers.cc.o)
```

# Ubuntu

@SJaffa can you add the Ubuntu error in a comment?

**Comment by SJaffa** [comment]
I don't get any warning about tiff conflicts. I do get:

`-- Found TIFF: /usr/local/lib/libtiff.so (found version "4.3.0") `

but it builds without errors and passes all tests.

**Comment by tkoskela** [comment]
Try removing `find_package(TIFF)` line from `CMakeLists.txt`. Then it should use the version conan has installed. If it happily builds with that, great! If not, let me know what the error is
