### ISSUE TITLE
Turn forward backward example into test

### ISSUE THREAD

**Issue by tkoskela** [astro-informatics/sopt#297]
The tests in tests/forward_backward.cc only test that the public members of `ImagingForwardBackward` have the correct types. We want to test that the `()` operator works correctly. There is an example in examples/forward_backward/inpainting.cc that we can use, we only need to add a check that the result is within reasonable tolerance of the original image

This will allow verifying that the refactoring in #284 is done correctly. We can then also use this test to develop the cppFlow interface.

**Comment by SJaffa** [comment]
All tests (or in fact all files) have a mix of `#include "thing"` and `#include <thing>`.  These do [slightly different things](https://cplusplus.com/doc/tutorial/preprocessor/) - <> for standard library and "" for files in the current working directory is the recommendation I think?
We could tidy them up to use the right ones for the right situations, if we have time.
