### ISSUE TITLE
Using #include "" for user provided headers

### ISSUE THREAD

**Issue by tkoskela** [astro-informatics/sopt#302]
In e.g. `tests` headers from `sopt` and `catch` are included with <>. It would make more sense to use "", although both seem to work.

**Comment by SJaffa** [comment]
Docs on the difference between "" and <>:

https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html#Include-Syntax
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#sf12-prefer-the-quoted-form-of-include-for-files-relative-to-the-including-file-and-the-angle-bracket-form-everywhere-else

We should maybe start writing this sort of stuff in a style guide/contribution guide?
