### ISSUE TITLE
Conan fails to install doxygenconfig.cmake on GHA runners

### ISSUE THREAD

**Issue by tkoskela** [astro-informatics/sopt#338]
Same issue found on @tkoskela Ubuntu 22.04 laptop with conan versions 1.54 -- 1.58. No `doxygenconfig.cmake` in build directory after `conan install`.

Works correctly on @SJaffa Ubuntu 20.04 laptop with conan versions 1.51 -- 1.58.

**Comment by SJaffa** [comment]
Opened an [issue on Conan repo](https://github.com/conan-io/conan/issues/13149) and they had some suggestions but I need to read up a bit on Conan stuff to implement it

**Comment by SJaffa** [comment]
Documentation on two profiles: https://docs.conan.io/1/reference/profiles.html#build-profiles-and-host-profiles
