### ISSUE TITLE
Reweighted meta-algorithm ||x||_1 to ||x||_0

### ISSUE THREAD

**Issue by mdavezac** [astro-informatics/sopt#85]
Tries to get close to ||x||_0 by re-weighting and rerunning the algorithm again and again.
See https://github.com/astro-informatics/sopt/blob/matlab/matlab/sopt_dr_rwBPDN.m
and https://github.com/astro-informatics/sopt/tree/matlab/matlab

**Comment by Luke-Pratley** [comment]
This is done as far as I know
